coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%

comment:
  layout: 'reach,diff,flags,tree,reach'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
