[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "argparse>=1.4.0",
    "marimo>=0.14.16",
    "numpy>=1.21.6",
    "pandas>=1.3.5",
    "plotly>=5.18.0",
]
