#!/bin/bash

# Clean the generated directory
echo "🧹 Cleaning generated code directory..."
rm -rf src/generated

# Create the generated directory
mkdir -p src/generated

# Generate TypeScript code from OpenAPI spec
echo "🔄 Generating TypeScript code from OpenAPI specification..."
docker run --rm \
  -v "${PWD}:/local" \
  --user "$(id -u):$(id -g)" \
  openapitools/openapi-generator-cli:v7.14.0 generate \
  -i https://petstore3.swagger.io/api/v3/openapi.json \
  -g typescript-axios \
  -o /local/src/generated \
  --additional-properties=supportsES6=true,withInterfaces=true,typescriptThreePlus=true,useSingleRequestParameter=true

echo "✅ Code generation completed successfully!"
echo "📁 Generated files are located in: src/generated/"

# Create a barrel export file for easier imports
echo "📦 Creating barrel export file..."
cat > src/generated/index.ts << 'EOF'
// This file is auto-generated by OpenAPI Generator
// Do not edit manually

export * from './api';
export * from './base';
export * from './common';
export * from './configuration';
EOF

echo "🎉 All done! You can now import the generated API client."
